#!/bin/sh

hash=$(lua /usr/bin/crc16)
h1=$(echo $hash | cut -d ' ' -f2)
h2=$(echo $hash | cut -d ' ' -f3)
echo -e $hash
echo -e $h1
echo -e $h2

[ -e '/root/kcfn32' ] && {
	ip="10.246.89.$h2" 
	uci set qmp.networks.lan_address="172.30.22.1"
	uci set qmp.networks.lan_netmask="255.255.255.0"
	uci set qmp.networks.bmx6_ipv4_address="$ip/32"
} || {
	ip="10.$h1.$h2.1"
	uci set qmp.networks.lan_address="$ip"
	uci set qmp.networks.lan_netmask="255.255.255.0"
	uci set qmp.networks.bmx6_ipv4_address="$ip/24"
}

uci set qmp.roaming.ignore=1

uci commit qmp

